// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uovkfmqvxremvhpbglvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvdmtmbXF2eHJlbXZocGJnbHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDY4NzksImV4cCI6MjA2OTc4Mjg3OX0.kHj8uEskUPi1-BUNdGeC_8OSDjnrw56WWAtnQDs2iS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});